name: rspec
on:
  pull_request:
    branches: [version-2]
jobs:
  run-rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 15
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/rails_test
      VITE_RUBY_AUTO_BUILD: false
    steps:
      - uses: actions/checkout@v4
      - name: Enable NodeJS Corepack support
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Preparing database
        run: bin/rails db:prepare
      - name: Precompile assets
        run: bin/rails assets:precompile
      - name: Run tests
        run: bin/rspec
